#!/usr/bin/env bash
# Ghoten Action — Summary: generate GitHub Job Summary
set -euo pipefail

COMMAND="${INPUT_COMMAND}"
WORKING_DIR="${INPUT_WORKING_DIRECTORY}"
WORKSPACE="${INPUT_WORKSPACE:-default}"
EXIT_CODE="${COMMAND_EXITCODE:-0}"
CHANGES="${PLAN_HAS_CHANGES:-false}"
FMT="${FMT_RESULT:-false}"

STDOUT_FILE="${RUNNER_TEMP}/ghoten_stdout.txt"
BACKEND_REPO_FILE="${RUNNER_TEMP}/ghoten_backend_repo.txt"
DURATION_FILE="${RUNNER_TEMP}/ghoten_duration.txt"

# ─── Read context ─────────────────────────────────────────────────────────────
OUTPUT=""
[[ -f "$STDOUT_FILE" ]] && OUTPUT=$(cat "$STDOUT_FILE")

BACKEND_REPO="${INPUT_BACKEND_REPOSITORY:-}"
[[ -z "$BACKEND_REPO" && -f "$BACKEND_REPO_FILE" ]] && BACKEND_REPO=$(cat "$BACKEND_REPO_FILE")

DURATION="—"
if [[ -f "$DURATION_FILE" ]]; then
  SECS=$(cat "$DURATION_FILE")
  if [[ $SECS -ge 60 ]]; then
    DURATION="$((SECS / 60))m $((SECS % 60))s"
  else
    DURATION="${SECS}s"
  fi
fi

# ─── Status ───────────────────────────────────────────────────────────────────
case "$COMMAND" in
  plan)
    if [[ "$EXIT_CODE" != "0" ]]; then
      EMOJI="❌"; STATUS="Failed"
    elif [[ "$CHANGES" == "true" ]]; then
      EMOJI="🔄"; STATUS="Changes detected"
    else
      EMOJI="✅"; STATUS="No changes"
    fi
    ;;
  apply)
    if [[ "$EXIT_CODE" != "0" ]]; then
      EMOJI="❌"; STATUS="Failed"
    else
      EMOJI="✅"; STATUS="Applied successfully"
    fi
    ;;
  destroy)
    if [[ "$EXIT_CODE" != "0" ]]; then
      EMOJI="❌"; STATUS="Failed"
    else
      EMOJI="🗑️"; STATUS="Destroyed"
    fi
    ;;
  fmt)
    if [[ "$FMT" == "true" ]]; then
      EMOJI="⚠️"; STATUS="Differences found"
    else
      EMOJI="✅"; STATUS="No differences"
    fi
    ;;
  validate)
    if [[ "$EXIT_CODE" != "0" ]]; then
      EMOJI="❌"; STATUS="Failed"
    else
      EMOJI="✅"; STATUS="Valid"
    fi
    ;;
  *)
    EMOJI="ℹ️"; STATUS="Completed"
    ;;
esac

# ─── Parse plan stats ────────────────────────────────────────────────────────
ADD="" CHG="" DEL=""
if [[ "$COMMAND" == "plan" && "$CHANGES" == "true" && -n "$OUTPUT" ]]; then
  ADD=$(grep -oE '[0-9]+ to add' <<< "$OUTPUT" | grep -oE '[0-9]+' || echo "0")
  CHG=$(grep -oE '[0-9]+ to change' <<< "$OUTPUT" | grep -oE '[0-9]+' || echo "0")
  DEL=$(grep -oE '[0-9]+ to destroy' <<< "$OUTPUT" | grep -oE '[0-9]+' || echo "0")
fi

# Parse apply stats
APPLY_STATS=""
if [[ "$COMMAND" == "apply" && "$EXIT_CODE" == "0" && -n "$OUTPUT" ]]; then
  APPLY_STATS=$(grep -oE '[0-9]+ added, [0-9]+ changed, [0-9]+ destroyed' <<< "$OUTPUT" || true)
fi

# ─── Truncate output ─────────────────────────────────────────────────────────
MAX_LEN=60000
TRUNCATED=""
if [[ ${#OUTPUT} -gt $MAX_LEN ]]; then
  OUTPUT="${OUTPUT:0:$MAX_LEN}"
  TRUNCATED=" *(truncated)*"
fi

# ─── Write summary ───────────────────────────────────────────────────────────
{
  echo "## ${EMOJI} \`${COMMAND}\` — ${STATUS}"
  echo ""

  # Metadata table
  echo "| | |"
  echo "|:--|:--|"
  echo "| **Command** | \`ghoten ${COMMAND}\` |"
  [[ "$WORKING_DIR" != "." ]] && echo "| **Directory** | \`${WORKING_DIR}\` |"
  [[ "$WORKSPACE" != "default" ]] && echo "| **Workspace** | \`${WORKSPACE}\` |"
  [[ -n "$BACKEND_REPO" ]] && echo "| **Backend** | \`${BACKEND_REPO}\` |"
  echo "| **Duration** | ${DURATION} |"
  [[ -n "$APPLY_STATS" ]] && echo "| **Resources** | ${APPLY_STATS} |"
  echo ""

  # Change statistics for plan
  if [[ "$COMMAND" == "plan" && "$CHANGES" == "true" && -n "$ADD" ]]; then
    echo "### Resource Changes"
    echo ""
    echo "| Action | Count |"
    echo "|:-------|------:|"
    echo "| 🟢 **Add** | ${ADD} |"
    echo "| 🟡 **Change** | ${CHG} |"
    echo "| 🔴 **Destroy** | ${DEL} |"
    echo ""
  fi

  # No-changes message
  if [[ "$COMMAND" == "plan" && "$CHANGES" == "false" && "$EXIT_CODE" == "0" ]]; then
    echo "> ✅ Infrastructure is up-to-date. No changes needed."
    echo ""
  fi

  # Output details
  if [[ -n "$OUTPUT" ]]; then
    echo "<details><summary>Full Output${TRUNCATED}</summary>"
    echo ""
    echo '```hcl'
    printf '%s\n' "$OUTPUT"
    echo '```'
    echo ""
    echo "</details>"
    echo ""
  fi

  echo "---"
  echo "<sub>Generated by <a href=\"https://github.com/vmvarela/ghoten\">Ghoten</a> · <a href=\"${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}\">${GITHUB_WORKFLOW} #${GITHUB_RUN_NUMBER}</a></sub>"

} >> "$GITHUB_STEP_SUMMARY"

echo "📊 Job Summary generated"
