# Copyright (c) The OpenTofu Authors
# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2023 HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

FROM scratch

ARG TARGETARCH

LABEL maintainer="Ghoten"

COPY --from=binaries linux/${TARGETARCH}/ghoten /usr/local/bin/ghoten

ENTRYPOINT ["/usr/local/bin/ghoten"]
