import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Introduction',
      link: {type: 'doc', id: 'intro/index'},
      items: [{type: 'autogenerated', dirName: 'intro'}],
    },
    {
      type: 'category',
      label: 'CLI',
      link: {type: 'doc', id: 'cli/index'},
      items: [{type: 'autogenerated', dirName: 'cli'}],
    },
    {
      type: 'category',
      label: 'Language',
      link: {type: 'doc', id: 'language/index'},
      items: [{type: 'autogenerated', dirName: 'language'}],
    },
    {
      type: 'category',
      label: 'Internals',
      link: {type: 'doc', id: 'internals/index'},
      items: [{type: 'autogenerated', dirName: 'internals'}],
    },
  ],
};

export default sidebars;
